version: 2

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: ./moody
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package
  system_packages: true